implement RegistrationServiceImpl class, add and implement UserUnchec…
mate-academy/jv-registration-validation pull request #1046
Opened 2024-10-07 14:08 UTC by skotsurskiy

…kedException class, RegistrationServiceImplTest class

2024-10-07 14:09 UTC, mateacademy-ai-mentor approved these changes
Great job on implementing the custom exception and the User class! Your code is well-structured and follows Java Bean conventions, making it easy to read and maintain. Keep up the good work! Remember, for future tests, consider edge cases and try to provide clear, specific feedback in your exceptions and error messages. 😊👍

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-10-07 15:02 UTC, Elena-Bruyako requested changes

2024-10-07 15:02 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +            if (person.getLogin().equals(user.getLogin())) {
```suggestion
        if (storageDao.get(user.getLogin()) != null)
```

2024-10-07 15:02 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +        storageDao.add(user);
```suggestion
        return storageDao.add(user);
```

2024-10-07 15:02 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +        return storageDao.get(user.getLogin());
```suggestion
```

2024-10-09 06:25 UTC, JJJazl requested changes

2024-10-09 06:25 UTC, JJJazl commented on src/test/java/core/basesyntax/RegistrationServiceImplTest.java
> +    void loginIsLessThanSixCharacters_notOk() {
Pay attention to the method names convetion for this task <methodUnderTest>_<state>_<expectedBehavior>
Example: register_loginIsLessThanSixCharacters_notOk()

2024-10-09 06:25 UTC, JJJazl commented on src/test/java/core/basesyntax/RegistrationServiceImplTest.java
> +    void passwordIsLessThanSixCharacters_notOk() {
Pay attention to the method names convetion

2024-10-09 06:25 UTC, JJJazl commented on src/test/java/core/basesyntax/RegistrationServiceImplTest.java
> +    void userRegister_ok() {
Pay attention to the method names convetion

2024-10-09 06:25 UTC, JJJazl commented on src/test/java/core/basesyntax/RegistrationServiceImplTest.java
> +    void ageIsLessThanEighteen_notOK() {
Pay attention to the method names convetion

2024-10-09 06:25 UTC, JJJazl commented on src/test/java/core/basesyntax/RegistrationServiceImplTest.java
> +    void registrationServiceNullValue_notOk() {
Pay attention to the method names convetion

2024-10-09 06:25 UTC, JJJazl commented on src/test/java/core/basesyntax/RegistrationServiceImplTest.java
> +    void loginNullValue_notOk() {
Pay attention to the method names convetion

2024-10-09 06:25 UTC, JJJazl commented on src/test/java/core/basesyntax/RegistrationServiceImplTest.java
> +    void passwordNullValue_notOk() {
Pay attention to the method names convetion

2024-10-09 06:25 UTC, JJJazl commented on src/test/java/core/basesyntax/RegistrationServiceImplTest.java
> +    void userIsNotExistInStorage() {
Pay attention to the method names convetion

2024-10-14 10:21 UTC, JJJazl approved these changes

2025-09-27 08:03 UTC, closed without merging