RegValidation HW Skarzhynets
mate-academy/jv-registration-validation pull request #119
Opened 2022-04-04 14:22 UTC by dSkarzh

2022-04-04 15:13 UTC, tanya-logatskaya commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +    }
If you don't pass dao implementation to the constructor, you can initialize it on field level

2022-04-04 15:13 UTC, tanya-logatskaya commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +        }
You can split null checks for more informative exception messages.
Just my thought, don't know if it's required)

2022-04-04 15:13 UTC, tanya-logatskaya commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +        return user;
You can simplify if-else construction here

2022-04-04 15:13 UTC, tanya-logatskaya commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_ValidUser_ReturnsSameUser() {
Missed Ok/NotOK

2022-04-04 15:13 UTC, tanya-logatskaya commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_ValidUser_UserAddedOnlyOneTime() {
Same

2022-04-04 15:13 UTC, tanya-logatskaya commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_ValidUser_UserAddedToDatabaseIsNotModified() {
And here

2022-04-05 03:31 UTC, tanya-logatskaya approved these changes

2022-04-05 06:51 UTC, Sofasmile requested changes

2022-04-05 06:51 UTC, Sofasmile commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        testUser.setAge(null);
краще створювати потрібний об'єкт користувача в кожному тестовому методі, щоб не потрібно було потім перезатерати поля. Адже якщо додасться нове поле, то можна забути очистити його тут

2022-04-05 06:51 UTC, Sofasmile commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_UserIsNull_NotOk() {
в деяких назвах методів текст після першого нижнього підкреслення написаний з великої літери, в деяких з малої. Давай зробимо все консистентним

2022-04-05 06:51 UTC, Sofasmile commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_ValidUser_ReturnsSameUser() {
погоджуюсь з Танею, якщо в решти методах використовуєш підхід з NotOk/Ok то краще це робити скрізь

2022-04-05 06:51 UTC, Sofasmile commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        testUser.setAge(LESS_THAN_MIN_AGE);
в тестах є нормальним використання простих числових/текстових значень. Для цього створювати константи не потрібно

також якщо мінімальним допустими значенням є 18 років, то в тесті `AgeLessThanMinimum` краще перевіряти критичне значення (тобто найближче до правильного), а це 17.

2022-04-05 06:51 UTC, Sofasmile commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        assertTrue(Storage.people.isEmpty());
що перевіряє цей тест?

2022-04-05 09:56 UTC, Sofasmile approved these changes

2023-01-20 08:39 UTC, closed without merging