Hw test
mate-academy/jv-registration-validation pull request #198
Opened 2022-06-16 13:08 UTC by Swyatik19

2022-06-16 13:52 UTC, MaliukDaria requested changes

2022-06-16 13:52 UTC, MaliukDaria commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
>      public User register(User user) {
lets add check for `user == null`

2022-06-16 13:52 UTC, MaliukDaria commented on src/test/java/core/basesyntax/HelloWorldTest.java
> +        user.setAge(21);
```suggestion
        Storage.people.clear();
        user.setAge(21);
```

we dont need to set id here(it set bystorageDao)

2022-06-16 13:52 UTC, MaliukDaria commented on src/test/java/core/basesyntax/HelloWorldTest.java
> +        registrationService = new core.basesyntax.service.RegistrationServiceImpl();
```suggestion
        registrationService = new RegistrationServiceImpl();
```

2022-06-16 13:52 UTC, MaliukDaria commented on src/test/java/core/basesyntax/HelloWorldTest.java
> +        registrationService.register(user);
lets add user to Storage directly(as we cant be sure that register method works correctly)

2022-06-16 13:52 UTC, MaliukDaria commented on src/test/java/core/basesyntax/HelloWorldTest.java
> +    void register_usersAgeLessThan18_notOk() {
```suggestion
    void register_usersAgeLessThanMinAge_notOk() {
```

2022-06-16 13:52 UTC, MaliukDaria commented on src/test/java/core/basesyntax/HelloWorldTest.java
> +    void register_usersPasswordLessThan6symbols_notOk() {
```suggestion
    void register_usersPasswordLessThanMinPasswordLength_notOk() {
```

2022-06-20 05:42 UTC, Nick97-git requested changes

2022-06-20 05:42 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +    public static final int MIN_PASSWORD_LENGTH = 6;
public -> private

2022-06-20 05:42 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +    public User equals(User user) {
don't need to create a separate method for this logic, move logic in this method directly to register method

2022-06-20 05:42 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +        }
use constants in messages

2022-06-20 05:42 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +            throw new RuntimeException("This field should not be empty");
which field?

2022-06-20 05:42 UTC, Nick97-git commented on src/test/java/core/basesyntax/HelloWorldTest.java
> +    void register_userExist_notOk() {
you should expect an exception here but right know it seems like register method works ok in such case

2022-06-20 17:18 UTC, Nick97-git requested changes
you have unresolved comments from my previous review, fix them

2022-06-21 15:59 UTC, Swyatik19 commented on src/test/java/core/basesyntax/HelloWorldTest.java
> +    void register_userExist_notOk() {
А чому один ментор дав задачу на виправлення ,я пофіксив все і потім ще раз інший ментор знову дає виправлення , був би дуже вдячний якби виправлення можна було за 1 раз зробити .

2022-06-22 16:04 UTC, Swyatik19 commented on src/test/java/core/basesyntax/HelloWorldTest.java
> +    void register_userExist_notOk() {
> (ви повинні очікувати виняток тут, але правильно знайте, здається, що метод реєстру працює нормально в такому випадку) , сорі але я не розумію що тут треба зробити???

2022-06-22 16:12 UTC, Nick97-git requested changes

2022-06-22 16:12 UTC, Nick97-git commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +            throw new RuntimeException("This field should not be empty");
повідомлення не інформативне, допиши в повідомлення що пароль і логін не мають бути пустими

2022-06-22 16:12 UTC, Nick97-git commented on src/test/java/core/basesyntax/HelloWorldTest.java
> +    void register_userExist_notOk() {
якщо користувач вже є в Storage, то має викидатися помилка, відповідно в тесті ти маєш її очікувати, а ти зараз цього не робиш

2024-03-18 17:09 UTC, closed without merging