RegistrationServiceImpl implemented. RegistrationServiceTest created …
mate-academy/jv-registration-validation pull request #287
Opened 2022-08-22 20:40 UTC by SpaceUrgent

…for testing ServiceImpl

2022-08-23 11:51 UTC, MaliukDaria requested changes

2022-08-23 11:51 UTC, MaliukDaria commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +            throw new RuntimeException("User must be at least 18 years old. Current age: " + age);
let's make all "magic numbers" as constants

2022-08-23 11:51 UTC, MaliukDaria commented on src/test/java/core/basesyntax/RegistrationServiceTest.java
> +    }
I think it's better to clean storage after every test

2022-08-23 11:51 UTC, MaliukDaria commented on src/test/java/core/basesyntax/RegistrationServiceTest.java
> +    }
lets add null check and throw some RuntimeException with informative exception message?

2022-08-23 11:51 UTC, MaliukDaria commented on src/test/java/core/basesyntax/RegistrationServiceTest.java
> +    private List<User> validUsers;
maybe we can make this variable local?

2022-08-23 11:51 UTC, MaliukDaria commented on src/test/java/core/basesyntax/RegistrationServiceTest.java
> +    private StorageDaoImpl dao;
```suggestion
    private StorageDaoImpl storageDao;
```

2022-08-23 11:51 UTC, MaliukDaria commented on src/test/java/core/basesyntax/RegistrationServiceTest.java
> +                () -> registrationService.register(userWithNullAge));
same here, lets add null check with RuntimeException, It is really strange to expect NPE

2022-08-23 11:51 UTC, MaliukDaria commented on src/test/java/core/basesyntax/RegistrationServiceTest.java
> +    public void register_userEmptyLogin_throwsRuntimeException() {
```suggestion
    public void register_userEmptyOrBlankLogin_notOk() {
```

2022-08-23 11:51 UTC, MaliukDaria commented on src/test/java/core/basesyntax/RegistrationServiceTest.java
> +    public void register_nullUser_throwsNullPointer() {
```suggestion
    public void register_nullUser_notOk() {
```

same for other test names

2022-08-23 11:51 UTC, MaliukDaria commented on src/test/java/core/basesyntax/RegistrationServiceTest.java
> +        registrationService.register(user);
lets add user to storage directly, in case the register() method does not work correctly

2022-08-23 11:51 UTC, MaliukDaria commented on src/test/java/core/basesyntax/RegistrationServiceTest.java
> +    public void register_userWithInvalidPassword_throwsRuntimeException() {
```suggestion
    public void register_passwordLengthLessThanMin_notOk() {
```

2022-08-26 09:01 UTC, MaliukDaria requested changes

2022-08-26 09:01 UTC, MaliukDaria commented on src/test/java/core/basesyntax/RegistrationServiceTest.java
> +@TestInstance(PER_CLASS)
why do we need this?

2022-08-26 09:01 UTC, MaliukDaria commented on src/test/java/core/basesyntax/RegistrationServiceTest.java
> +    @AfterAll
I think we should do this after each test

2022-08-26 16:07 UTC, aaananas requested changes

2022-08-26 16:07 UTC, aaananas commented on src/test/java/core/basesyntax/RegistrationServiceTest.java
> +
```suggestion
    private RegistrationServiceImpl registrationService;
    private StorageDaoImpl storageDao;
```
move initialization to a method with annotation BeforeAll or BeforeClass (depends on version)

2022-08-26 17:12 UTC, aaananas approved these changes

2025-03-09 18:12 UTC, closed without merging