try commit 19/12
mate-academy/jv-registration-validation pull request #401
Opened 2022-12-18 23:43 UTC by Watxesnavo

2022-12-19 16:16 UTC, aleksandr-bevza requested changes
![image](https://user-images.githubusercontent.com/117547096/208470642-214c11a5-3a82-4a95-b115-ea0538164c3b.png)
Looks like some tests fail. Fix this tests please

2022-12-22 11:28 UTC, aleksandr-bevza requested changes

2022-12-22 11:28 UTC, aleksandr-bevza commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +            throw new CustomException("password length must be more than 6");
1. Use "MIN_PASSWORD_LENGTH" in message
2. Message is not correct. You say: "password length must be more than 6" It means that length 6 is not correct, but length 7 is correct

2022-12-22 11:28 UTC, aleksandr-bevza commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +            throw new CustomException("that user already exist in storage");
Include user's login to this message

2022-12-22 11:28 UTC, aleksandr-bevza commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    private static final int MIN_PASS_LENGTH = 6;
```suggestion
    private static final int MIN_PASSWORD_LENGTH = 6;
```

2022-12-22 11:28 UTC, aleksandr-bevza commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        Storage.people.remove(user1);
Delete it in all places. Use @AfterEach instead
```suggestion
```

2022-12-22 11:28 UTC, aleksandr-bevza commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +
```suggestion
@AfterEach
void tearDown() {
    Storage.people.clear();
}
```

2022-12-22 11:28 UTC, aleksandr-bevza commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_UserExistsAlready_Ok() {
Is it really "ok"? (last part of method's name). Looks like we check "notOk" behavior in this test

2022-12-22 11:28 UTC, aleksandr-bevza commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_UserAgeNotOk_ThrowsException_Ok() {
![image](https://user-images.githubusercontent.com/117547096/209124201-92fd510c-c52b-4e0a-9ba4-1df3e7d39414.png)

Please, follow the naming requirements for this homework:
```suggestion
    void register_AgeLessThan18_NotOk() {
```

2022-12-22 11:28 UTC, aleksandr-bevza commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_UserLoginNull_ThrowsException_Ok() {
Please, follow the naming requirements for this homework:
Fix in all places
```suggestion
    void register_LoginIsNull_NotOk() {
```

2022-12-22 11:28 UTC, aleksandr-bevza commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        Assertions.assertTrue(user1.getAge() > MIN_AGE);
```suggestion
        Assertions.assertTrue(user1.getAge() >= MIN_AGE);
```

2022-12-22 11:28 UTC, aleksandr-bevza commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        Assertions.assertTrue(user1.getPassword().length() > MIN_PASS_LENGTH);
```suggestion
        Assertions.assertTrue(user1.getPassword().length() >= MIN_PASS_LENGTH);
```

2022-12-23 11:25 UTC, aleksandr-bevza requested changes

2022-12-23 11:25 UTC, aleksandr-bevza commented on src/main/java/core/basesyntax/service/RegistrationService.java
> +    User register(User user) throws RegisterException;
No need to add unchecked exception to method signature (throws)
```suggestion
    User register(User user);
```

2022-12-24 12:27 UTC, nacenik requested changes

2022-12-24 12:27 UTC, nacenik commented on pom.xml
> -            <version>${junit-jupiter.version}</version>
don't change pom file.

2022-12-24 12:27 UTC, nacenik commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +    private static final int MIN_PASS_LENGTH = 6;
Make constant name more informative

2022-12-26 10:15 UTC, aleksandr-bevza approved these changes

2022-12-26 10:15 UTC, aleksandr-bevza commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_UserPasswordLength_ThrowsException_Ok() {
```suggestion
    void register_SmallPasswordLength_NotOk() {
```

2022-12-26 10:15 UTC, aleksandr-bevza commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_UserPasswordNull_ThrowsException_Ok() {
```suggestion
    void register_UserPasswordNull_NotOk() {
```

2024-10-31 17:42 UTC, closed without merging