solution for Registration Service
mate-academy/jv-registration-validation pull request #661
Opened 2023-07-18 16:14 UTC by vladis9

2023-07-18 16:53 UTC, kozhukhovsky requested changes

2023-07-18 16:53 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +            throw new RuntimeException("Data must be filled");
It is better to create your own exception, for example RegistrationException

2023-07-18 16:53 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
>      public User register(User user) {
add check
![image](https://github.com/mate-academy/jv-registration-validation/assets/12864128/6303a64e-5297-46a6-8235-195e5c823436)

2023-07-18 16:53 UTC, kozhukhovsky commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void valid_user_Ok() {
rename all method with this pattern
![image](https://github.com/mate-academy/jv-registration-validation/assets/12864128/ce25c4c7-10ec-4c42-8709-ee8c3470b71e)

2023-07-18 16:53 UTC, kozhukhovsky commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +class RegistrationServiceImplTest {
add new test for check with same login

2023-07-18 16:54 UTC, kozhukhovsky requested changes
For platform

2023-07-19 11:06 UTC, okuzan requested changes
You should test edge cases
![image](https://github.com/mate-academy/jv-registration-validation/assets/49767049/e4cbc903-63cd-4dae-956a-a5cb44418e2f)

2023-07-19 11:06 UTC, okuzan commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    public void register_underAge_notOk() {
```suggestion
    public void register_underageUser_notOk() {
```

2024-05-29 11:06 UTC, closed without merging