jv-registration-validation HW solution
mate-academy/jv-registration-validation pull request #769
Opened 2023-10-02 14:26 UTC by luk14n

2023-10-03 09:49 UTC, Rommelua requested changes

2023-10-03 09:49 UTC, Rommelua commented on src/main/java/core/basesyntax/service/InvalidRegistrationDataException.java
> +public class InvalidRegistrationDataException extends RuntimeException {
```suggestion
public class RegistrationException extends RuntimeException {
```

2023-10-03 09:49 UTC, Rommelua commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +    private static final int DEFAULT_USER_PASSWORD_SIZE = 6;
```suggestion
    private static final int MIN_USER_LOGIN_SIZE = 6;
    private static final int MIN_USER_PASSWORD_SIZE = 6;
```

2023-10-03 09:49 UTC, Rommelua commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +    private static final int MINIMUM_USER_AGE = 18;
```suggestion
    private static final int MIN_USER_AGE = 18;
```

2023-10-03 09:49 UTC, Rommelua commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        int newUserAge = 23;
remove this local vars

2023-10-03 09:49 UTC, Rommelua commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_null_user_NotOk() {
```suggestion
    void register_nullUser_NotOk() {
```

2023-10-03 09:49 UTC, Rommelua commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_null_login_NotOk() {
```suggestion
    void register_nullLogin_NotOk() {
```

2023-10-03 09:49 UTC, Rommelua commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +                () -> registrationService.register(user));
![image](https://github.com/mate-academy/jv-registration-validation/assets/20326858/acefe07d-9576-4ae0-86ae-eb9f015b1a1b)

2023-10-03 09:49 UTC, Rommelua commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        user.setPassword("123");
![image](https://github.com/mate-academy/jv-registration-validation/assets/20326858/68707589-336b-47e0-bd8f-a7866a4167c5)

2023-10-03 09:49 UTC, Rommelua commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        register.setPassword("Password");
![image](https://github.com/mate-academy/jv-registration-validation/assets/20326858/7562b554-d457-432a-bc75-3b0e408ae2dd)

2023-10-03 15:06 UTC, Rommelua requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2023-10-03 15:06 UTC, Rommelua commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        assertThrows(RuntimeException.class,
```suggestion
        assertThrows(RegistrationException.class,
```

2023-10-03 15:06 UTC, Rommelua commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    void register_invalid_login_NotOk() {
```suggestion
    void register_invalidLogin_NotOk() {
```
![image](https://github.com/mate-academy/jv-registration-validation/assets/20326858/b3b6dd6d-0120-4903-bb75-a266e0a0cb3f)

2023-10-03 15:06 UTC, Rommelua commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +                () -> registrationService.register(user));
![image](https://github.com/mate-academy/jv-registration-validation/assets/20326858/508ad6af-c0e2-4739-abda-dc395ab142da)

2023-10-03 17:23 UTC, luk14n commented
> Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

Ok, I will pay attention in the future. Forgive my inattention

2023-10-03 17:26 UTC, Rommelua requested changes
![image](https://github.com/mate-academy/jv-registration-validation/assets/20326858/2c69f40b-c31e-4adf-b7df-ec9509372538)

Java Cl checks failed. Before making a Pull Request (or a new commit to an already existing PR), you need to write the mvn clean package command in the terminal and make sure that all checks pass. After that, the mentor will be able to review the homework

2023-10-03 18:06 UTC, luk14n commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +            user.setAge(18);
![image](https://github.com/mate-academy/jv-registration-validation/assets/110618327/93fd119e-7a36-4623-8e36-32e7922eba57)
Can you than elaborate, please, more precisely what changes here is required? It seems to me that all edge cases is handled properly

2023-11-01 15:32 UTC, Sanderfuck requested changes

2023-11-01 15:32 UTC, Sanderfuck commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +                    RegistrationException("Age cannot be negative number!");
![image](https://github.com/mate-academy/jv-registration-validation/assets/63095184/9cdbe540-4624-4cd1-af93-27367ead37bb)
You already have validation

2023-11-01 15:32 UTC, Sanderfuck commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +            throw new
You can divide logic of validation age, password, login to helpful private methods

2023-11-01 15:32 UTC, Sanderfuck commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        userAge18.setAge(18);
Better save magic numbers in constant and correct naming of userValidAge or like this

2023-11-01 15:32 UTC, Sanderfuck commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    }
Save strings to constant

2023-11-02 09:50 UTC, Sanderfuck approved these changes

2023-11-02 10:18 UTC, closed without merging