Hw solution
mate-academy/jv-registration-validation pull request #77
Opened 2022-02-01 16:41 UTC by Sasha-Bachynskyi

2022-02-05 07:33 UTC, LinkClink requested changes

2022-02-05 07:33 UTC, LinkClink commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +        return user;
in task we must add new user to storageDao when user success register))

2022-02-05 08:03 UTC, LinkClink approved these changes
Good

2022-02-07 09:03 UTC, KostyaNikiforov requested changes

2022-02-07 09:03 UTC, KostyaNikiforov commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +    }
This test does the same as the previous one

2022-02-07 09:03 UTC, KostyaNikiforov commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        user2.setAge(25);
You use it only in one test method, so there is no need to do this logic before each

2022-02-07 09:59 UTC, KostyaNikiforov requested changes

2022-02-07 09:59 UTC, KostyaNikiforov commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +        }
Better move this logic to a separate methods

2022-02-07 09:59 UTC, KostyaNikiforov commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +
Empty line

2022-02-07 09:59 UTC, KostyaNikiforov commented on src/test/java/core/basesyntax/service/RegistrationServiceImplTest.java
> +        });
```suggestion
        assertThrows(RuntimeException.class, 
            () -> registrationService.register(user);
        );
```

2022-02-07 10:40 UTC, KostyaNikiforov approved these changes

2022-02-07 10:40 UTC, KostyaNikiforov commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +        return storageDao.add(user);
```suggestion
        validateUserAge(user);
        validateUserPassword(user);
        validateUserLogin(user);
        return storageDao.add(user);
```

2025-08-07 15:25 UTC, closed without merging