initial commit
mate-academy/jv-registration-validation pull request #827
Opened 2023-11-16 15:19 UTC by tsuki99

2023-11-16 15:33 UTC, olekskov requested changes

2023-11-16 15:33 UTC, olekskov commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +            throw new InvalidDataException("Incorrect data, try again!");
Should user guess what is wrong?
Please add meaningful information to your validation so user can read your message and know what to fix

2023-11-17 15:39 UTC, kozhukhovsky requested changes

2023-11-17 15:39 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +        if (!isUserPassCriterias(user)) {
what if user is null?

2023-11-20 15:41 UTC, Rommelua requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2023-11-20 15:41 UTC, Rommelua commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +            throw new NullPointerException();
never throw NullPointerException

![image](https://github.com/mate-academy/jv-registration-validation/assets/20326858/68bd1a07-dbe2-4c26-9f83-6a45f43ccc36)

2023-11-20 15:41 UTC, Rommelua commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +    private boolean isUserPassCriterias(User user) {
delete this method

2023-11-20 15:41 UTC, Rommelua commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +        for (User user : Storage.people) {
remove loop from this method

2023-11-20 15:41 UTC, Rommelua commented on src/main/java/core/basesyntax/service/RegistrationServiceImpl.java
> +                        + " enter the new one, higher or equal than 18.");
![image](https://github.com/mate-academy/jv-registration-validation/assets/20326858/3c8c88ba-25ab-4e1e-ac6f-106ff64fff7f)

2023-11-20 15:41 UTC, Rommelua commented on src/main/java/core/basesyntax/service/InvalidDataException.java
> +public class InvalidDataException extends RuntimeException {
```suggestion
public class RegistrationException extends RuntimeException {
```

2023-11-25 10:06 UTC, olekskov approved these changes
Good job

2025-10-08 19:13 UTC, closed without merging